config/routes.rb
Chessable::Application.routes.draw do

  get "subscriptions/new"

  root :to => 'home#index'
  match '/forbidden' => 'home#forbidden', :as => :forbidden
  match '/terms' => 'home#terms', :as => :terms
  match '/privacy' => 'home#privacy', :as => :privacy
  match '/more-info' => 'home#more_info', :as => :more_info

  resources :users, :path => :players do
    match '/dashboard' => 'dashboards#index'
    
    collection do
      get 'random'
    end

    resources :notifications, :only => [:update]
    resources :subscriptions, :only => [:new]
  end

  resources :games, :except => [:new, :edit] do
    resources :comments, :only => [:create]
  end

  resources :game_invites, :only => [:create, :update, :show, :destroy]
  resources :sessions
  resources :password_resets
  resources :payment_notifications, :only => [:create]

  resources :verifications, :only => [:index]

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword
  include Mongoid::Slug
  
  has_secure_password

  before_create :generate_verification_token
  after_create :send_welcome_email

  has_many :white_games, :class_name => 'Game', :inverse_of => :white_player
  has_many :black_games, :class_name => 'Game', :inverse_of => :black_player
  has_many :notifications
  has_many :subscriptions
  has_many :payment_notifications

  field :email
  field :username
  field :password_digest
  field :receive_email_notifications, :type => Boolean, :default => true
  field :auth_token
  field :password_reset_token
  field :password_reset_sent_at
  field :verification_token
  field :verified, :type => Boolean, :default => false

  field :wins_as_white, :default => 0
  field :wins_as_black, :default => 0
  field :losses_as_white, :default => 0
  field :losses_as_black, :default => 0
  field :draws_as_white, :default => 0
  field :draws_as_black, :default => 0
  
  slug :username

  attr_accessible :email, :username, :password, :password_confirmation
  attr_accessor :wins, :draws, :losses

  # filters
  before_create { generate_token(:auth_token) }

  # validations
  validates :password, 
            :presence => true,
            :length => { :minimum => 8 },
            :on => :create

  validates :password,
            :allow_blank => true,
            :length => { :minimum => 8 },
            :confirmation => true,
            :on => :update


  validates :email, :presence => true, :uniqueness => true, :email_format => true
  validates :username,
            :presence => true,
            :uniqueness => true,
            :format => { :with => /[A-Za-z0-9]+/ },
            :length => { :minimum => 2, :maximum => 24 }

  def games
    (white_games + black_games).sort_by { |game| game.updated_at }.reverse!
  end
  
  def active_games
    games.select { |game| game.active }
  end
  
  def won_games
    games.select { |game| self == game.winner }
  end
  
  def lost_games
    games.select { |game| self != game.winner && !game.active }
  end
  
  def drew_games
    games.select { |game| game.in_draw }    
  end

  def unread_notifications
    notifications.where(:read => false)
  end

  def current_subscription
    subscriptions.where(:current => true).first
  end

  def pending_game_invites
    GameInvite.all_of(:invited_id => id, :invite_status => GameInvite::INVITE_STATUS[:pending])
  end

  def sent_invites
    GameInvite.all_of(:inviter_id => id, :invite_status => GameInvite::INVITE_STATUS[:pending])
  end
  
  # Cumulative results
  def wins
    wins_as_white + wins_as_black
  end
  
  def losses
    losses_as_white + losses_as_black
  end
  
  def draws
    draws_as_white + draws_as_black
  end

  def generate_token(column)
  	begin
  		self[column] = SecureRandom.urlsafe_base64
  	end while User.exists?(conditions: { column: self[column]})  	
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.now.utc
    save!
    UserMailer.password_reset(self).deliver
  end

  private

  def generate_verification_token
    generate_token(:verification_token)
  end

  def send_welcome_email
    UserMailer.welcome(self).deliver    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :update]
  before_filter :authorize_user, :only => [:edit, :update]

  def random
    user = current_user

    until user != current_user
      user = User.skip(rand(User.count)).limit(1).first
    end

    redirect_to user_path(user)
  end

  def index
    if params[:search]
      @users = User.all.where(:username => /#{Regexp.escape(params[:search])}/i).to_a
    else    
      @users = User.all.to_a
      # @users.delete current_user if current_user
    
      case params[:sort_by]
      when /username/
        @users.sort_by! { |user| user.username.downcase }
        @sorted_by = 'username'
      when /most_wins/
        @users.sort! { |a, b| a.wins <=> b.wins }.reverse!
        @sorted_by = 'wins'
      when /most_losses/
        @users.sort! { |a, b| a.losses <=> b.losses }.reverse!
        @sorted_by = 'losses'
      when /most_draws/
        @users.sort! { |a, b| a.draws <=> b.draws }.reverse!
        @sorted_by = 'draws'
      else
        @users.sort! { |a, b| a.wins <=> b.wins }.reverse!
        @sorted_by = 'wins'
      end
    end
  end

  def show
    @user = User.find_by_slug(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(params[:user])
    @user.username.strip!
    if @user.save
      redirect_to root_path, :notice => 'A verification email has been sent. Verify your account by clicking the link within the email.'
    else
      render 'new'
    end
  end

  def update
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    @user.receive_email_notifications = params[:user][:receive_email_notifications]

    if @user.save!
      redirect_to edit_user_path(@user), :notice => 'Account settings updated.'
    else
      render 'edit'
    end
  end

  private

  def authorize_user
    @user = User.find_by_slug(params[:id])
    redirect_to forbidden_path unless @user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :title do %>
  account settings - chessable
<% end %>

<section id="account_settings">
  <% if @user.errors.any? %>
    <div class="six columns alpha">
      <div id="error_explanation" class="panel error">
        <h2>Your details are invalid.</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <h2 class="underlined_header">Account Settings</h2>

  <%= form_for @user do |f| %>

    <div class="form_container sixteen columns alpha omega">
      <div class="seven columns alpha field_container" id="avatar_settings">
        <h3>Avatar settings</h3>
        <div class="panel">
          <%= image_tag avatar_url(@user), :id => 'your_avatar' %>
        </div>
        <p id="gravatar">Your avatar is retreived using your <a href="http://en.gravatar.com/">Gravatar</a> account. 
          If you want to change your avatar, you can do so using Gravatar website.</p>
        <p>If you do not have a Gravatar account, and want an avatar, sign up for a Gravatar account with the same
          email address that you signed up to <%= link_to 'chessable', root_url %> with.</p>
      </div>
      
      <div class="offset-by-one four columns field_container">
        <h3>Notification settings</h3>

        <div class="field">
          <%= f.label :receive_email_notifications, 'Receive email notifications from chessable, notifying you about game invites, moves made, and other game events.' %><br>
          <%= f.check_box :receive_email_notifications %>
        </div>
      </div>
      
      <div class="four columns omega field_container" id="password_settings">
        <h3>Password settings
          <span class="note">(Leave blank if not changing.)</span>
        </h3>

        <div class="field">
          <%= f.label :password, 'New Password' %><br>
          <%= f.password_field :password %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, 'Password confirmation' %><br>
          <%= f.password_field :password_confirmation %>
        </div>
      </div>

      <div class="actions"><%= f.submit 'Update account settings' %></div>
    </div>

  <% end %>
</section>

<div class="clear"></div>

<section id="subscription_settings" class="sixteen columns alpha omega">
  <h2 class="underlined_header">Subscription information</h2>

  <% if @user.current_subscription %>
    <div class="seven columns alpha">
      <p>You currently have a subscription to <strong>chessable plus.</strong></p>
      <p>The current subscription period began on the <strong><%= @user.current_subscription.start_date.to_s(:british_date) %></strong>,
        and will end on the <strong><%= @user.current_subscription.end_date.to_s(:british_date) %></strong>.</p>
    </div>

    <div class="offset-by-three six columns omega" id="cancel_subscription">
      <p>There are <strong>no refunds</strong> if you decided to cancel this subscription, however there are also no cancellation fees.</p>
      <div id="cancel_text">
        <p>To cancel your subscription, you <strong>must log in to your PayPal account and cancel it there</strong>. 
          We will alert you when we have received your cancellation.</p>
      </div>
    </div>

  <% else %>
    <p>You currently have no subscription with chessable.</p>
    <p><strong>Upgrade</strong> to the <%= link_to 'plus plan', new_user_subscription_path(@user) %>
      to get access to extra features.</p>
  <% end %>
  
  <div class="clear"></div>
  
  <div class="six columns alpha">
    <% unless @user.subscriptions.empty? %>
        <h3>Subscription history</h3>

        <div class="six columns alpha">
          <table id="subscription_history">
            <tr>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Paid</th>
              <th>Cancelled</th>
            </tr>
            <% @user.subscriptions.each do |sub| %>
              <tr>
                <td><%= sub.start_date.to_s(:british_date) %></td>
                <td><%= sub.end_date.to_s(:british_date) %></td>
                <td><%= sub.paid %></td>
                <td><%= sub.cancelled %></td>
              </tr>
            <% end %>
          </table>
          <p class="note">Please be aware that this subscription information may take a while to become up-to-date.</p>
        </div>
    <% end %>
  </div>
  
</section>

app/views/users/index.html.erb
<% content_for :title do %>
  players - chessable
<% end %>

<section id="player_list">
  <h2 class="underlined_header">All players</h2>
  
  <div class="seven columns alpha omega">
    <div id="player_search">
      <%= form_tag users_path, :method => :get do %>
        <%= text_field_tag :search, params[:search], :placeholder => 'Search for username' %><%= submit_tag 'Search' %>
      <% end %>
    </div>
  </div>
  
  <div id="sort_menu">
    <h3>Sort by</h3>
    <ul>
      <li <%= 'class=current_sort' if @sorted_by == 'username' %>><%= link_to 'username', users_path(:sort_by => 'username') %></li>
      <li <%= 'class=current_sort' if @sorted_by == 'wins' %>><%= link_to 'most wins', users_path(:sort_by => 'most_wins') %></li>
      <li <%= 'class=current_sort' if @sorted_by == 'losses' %>><%= link_to 'most losses', users_path(:sort_by => 'most_losses') %></li>
      <li <%= 'class=current_sort' if @sorted_by == 'draws' %>><%= link_to 'most draws', users_path(:sort_by => 'most_draws') %></li>
    </ul>
  </div>
  
  <div class="twelve columns alpha">
    <% if @users.empty? %>
      <p>No players found, sorry. Click <%= link_to 'here', users_path %> to see all the players.</p>
    <% else%>
      <div class="cols_container">
        <% @users.each do |user| %>
        <div class="six columns">
          <%= render :partial => 'shared/user_preview', :locals => { :user => user } %>
        </div>
        <% end %>
      </div>	
    </div>
  <% end %>

</section>

app/views/users/new.html.erb
<div class="nine columns alpha omega">
  
  <% if @user.errors.any? %>
    <div class="five columns omega" id="error_container">
      <div id="error_explanation" class="panel error">
        <h2>Your details are invalid.</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <div class="four columns alpha">
    <div id="sign_up" class="panel">
      <%= form_for @user do |f| %>
        <h2>Sign up</h2>
        <div class="field">
          <%= f.label :email %><br>
          <%= f.email_field :email, :placeholder => 'email@example.com' %>
        </div>
        <div class="field">
          <%= f.label :username %><br>
          <%= f.text_field :username, :placeholder => 'username' %>
        </div>
        <div class="field">
          <%= f.label :password %><br>
          <%= f.password_field :password, :placeholder => '$3curEpassw0rd' %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation %>
        </div>

        <div class="actions">
          <span class="right"><%= f.submit %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title do %>
  <%= @user.username %>&#8217;s profile - chessable
<% end %>

<div id="profile">
  <h2 class="underlined_header"><%= @user.username %>'s profile</h2>

  <div class="eight columns alpha">
    <section id="user_details">
      <div id="avatar" class="panel">
        <%= image_tag avatar_url(@user), :class => 'avatar_full' %>
      </div>

      <p>
        <strong>Joined on:</strong> <%= @user.created_at.to_s(:british_date) %><br><br>
        <%
          if @user.white_games.count == @user.black_games.count
            most_played_as = 'both'
          else
            most_played_as = @user.white_games.count > @user.black_games.count ? 'White' : 'Black'
          end
        %>
        <strong>Most often plays as:</strong> <%= most_played_as %><br>
        <strong>Games currently being played:</strong> <%= @user.active_games.count %><br>
        <strong>Games finished:</strong> <%= @user.games.select { |game| game.game_over }.count %>
      </p>

      <% if current_user && current_user != @user %>
      <%= form_for :game_invite, :url => game_invites_path do |f| %>
      <%= f.hidden_field :invited, :value => @user.to_param %>

      <%= f.submit 'Challenge to a game' %>
      <% end %>
      <% end %>
    </section>
  </div>

  <div class="offset-by-two six columns omega">
    <section id="statistics">
      <p id="results_header">Results:</p>
      <table>
        <tr>
          <th>&nbsp;</th>
          <th>Wins</th>
          <th>Losses</th>
          <th>Draws</th>
        </tr>
        <tr>
          <th>White</th>
          <td><%= @user.wins_as_white %></td>
          <td><%= @user.losses_as_white %></td>
          <td><%= @user.draws_as_white %></td>
        </tr>
        <tr>
          <th>Black</th>
          <td><%= @user.wins_as_black %></td>
          <td><%= @user.losses_as_black %></td>
          <td><%= @user.draws_as_black %></td>
        </tr>
        <tr>
          <th>Totals</th>
          <td><strong><%= @user.wins %></strong></td>
          <td><strong><%= @user.losses %></strong></td>
          <td><strong><%= @user.draws %></strong></td>
        </tr>
      </table>
    </section>
  </div>

  <div class="clear"></div>

  <% unless @user.won_games.empty? %>
    <section class="sixteen columns alpha omega" id="won_games">
      <h3>Games <%= @user.username %> has won</h3>
      <div class="cols_container">
        <% @user.won_games.each do |game| %>
          <%= render :partial => 'shared/game_preview', :locals => { :game => game } %>
        <% end %>
      </div>
    </section>
  <% end %>

  <% unless @user.lost_games.empty? %>
    <section class="sixteen columns alpha omega" id="lost_games">
      <h3>Games <%= @user.username %> has lost</h3>
      <div class="cols_container">
        <% @user.lost_games.each do |game| %>
          <%= render :partial => 'shared/game_preview', :locals => { :game => game } %>
        <% end %>
      </div>
    </section>
  <% end %>

  <% unless @user.drew_games.empty? %>
    <section class="sixteen columns alpha omega" id="won_games">
      <h3>Games <%= @user.username %> has drew</h3>
      <div class="cols_container">
        <% @user.drew_games.each do |game| %>
          <%= render :partial => 'shared/game_preview', :locals => { :game => game } %>
        <% end %>
      </div>
    </section>
  <% end %>
  
</div>