config/routes.rb
Chessable::Application.routes.draw do

  get "subscriptions/new"

  root :to => 'home#index'
  match '/forbidden' => 'home#forbidden', :as => :forbidden
  match '/terms' => 'home#terms', :as => :terms
  match '/privacy' => 'home#privacy', :as => :privacy
  match '/more-info' => 'home#more_info', :as => :more_info

  resources :users, :path => :players do
    match '/dashboard' => 'dashboards#index'
    
    collection do
      get 'random'
    end

    resources :notifications, :only => [:update]
    resources :subscriptions, :only => [:new]
  end

  resources :games, :except => [:new, :edit] do
    resources :comments, :only => [:create]
  end

  resources :game_invites, :only => [:create, :update, :show, :destroy]
  resources :sessions
  resources :password_resets
  resources :payment_notifications, :only => [:create]

  resources :verifications, :only => [:index]

end

app/views/shared/_game_preview.html.erb
<div class="four columns game_preview_wrapper">
  <div class="game_preview panel">
    <div class="internal_wrapper">
      <span class="font_preloader">&nbsp;</span>
      <div class="preview_image">
        <a href="<%= game_path(game) %>">
          <canvas id="game_preview_<%= game.id %>">
          </canvas>
          <script type="text/javascript">
            $(window).load(function() {
                var gamepreview = new Application.GamePreview($('#game_preview_<%= game.id %>'),
                  "<%= "#{escape_javascript(game.pgn)}" %>",
                  "<%= "#{escape_javascript(game.fen)}" %>",
                  "<%= true if game.black_player == current_user %>");
            });
            </script>
          </a>
      </div>
      <div class="game_details">
        <p class="title"><%= link_to "#{game.white_player.username} vs. #{game.black_player.username}", game_path(game) %></p>
        <p class="times">updated: <strong><%= game.updated_at.to_s(:british_date) %></strong><br>
          <span class="quiet">started: <strong><%= game.created_at.to_s(:british_date) %></strong></span></p>

        <div class="result">
          <% if game.game_over %>
            <% if game.in_draw %>
              <p><strong>Game ended as a draw.</strong></p>
            <% else %>
              <p><strong>Winner: <%= link_to game.winner.username, user_path(game.winner) %></strong></p>
            <% end %>
          <% end %>
        </div>

        <% if @user && !game.game_over && game.next_player == @user %>
          <p class="turn_indicator"><%= link_to 'It is your turn.', game_path(game) %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <div class="sixteen columns">
      <nav class="navigation_bar">
        <a href="/"><p id="logo">chessable</p></a>
        <% if current_user %>
          <div id="inline_links">
            <ul>
              <li id="top"><a href="#">find &darr;</a>
                <ul>
                  <li><%= link_to 'random player', random_users_path %></li>
                  <li><%= link_to 'players', users_path %></li>
                  <li><%= link_to 'games', games_path %></li>
                </ul>
              </li>
            </ul>
          </div>
                    
          <div id="account_links">
            <ul>
              <li class="on">
                <a href="#"><%= current_user.username %>
                  <% unless current_user.unread_notifications.empty? %><span class="notifications_flag">&#9873;</span><% end %>
                </a>
                <ul>
                  <li>
                    <a href="<%= user_dashboard_path(current_user) %>">Dashboard<%= " (#{current_user.unread_notifications.count + current_user.pending_game_invites.count})" unless 
                    current_user.unread_notifications.empty? && current_user.pending_game_invites.empty? %></a>
                  </li>
                  <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                  <li><%= link_to 'Sign out', session_path(current_user), :method => :delete %></li>
                </ul>
              </li>
            </ul>
          </div>
        <% else %>
          <div id="account_links">
            <ul>
              <li id="sign_up"><%= link_to 'Sign up!', new_user_path %></li>
              <li id="sign_in"><%= link_to 'Sign in', new_session_path %></li>
            </ul>
          </div>
        <% end %>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_user_preview.html.erb
<div class="user_preview panel">
  <div class="avatar">
    <%= image_tag avatar_url(user) %>
  </div>
  <div class="details">
    <ul>
      <li class="user_link"><strong><%= link_to user.username, user_path(user) %></strong><br></li>
      <li><strong>Games unfinished:</strong> <%= user.active_games.count %><br></li>
      <li><strong>Games finished:</strong> <%= user.games.select { |game| game.game_over }.count %><br></li>
      <li><strong>W/L/D: </strong> <%= "#{user.wins}/#{user.losses}/#{user.draws}" %></li>
    </ul>
  </div>
</div>