config/routes.rb
Chessable::Application.routes.draw do

  get "subscriptions/new"

  root :to => 'home#index'
  match '/forbidden' => 'home#forbidden', :as => :forbidden
  match '/terms' => 'home#terms', :as => :terms
  match '/privacy' => 'home#privacy', :as => :privacy
  match '/more-info' => 'home#more_info', :as => :more_info

  resources :users, :path => :players do
    match '/dashboard' => 'dashboards#index'
    
    collection do
      get 'random'
    end

    resources :notifications, :only => [:update]
    resources :subscriptions, :only => [:new]
  end

  resources :games, :except => [:new, :edit] do
    resources :comments, :only => [:create]
  end

  resources :game_invites, :only => [:create, :update, :show, :destroy]
  resources :sessions
  resources :password_resets
  resources :payment_notifications, :only => [:create]

  resources :verifications, :only => [:index]

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_filter :authenticate_user!

  def index
  	@user = current_user
  end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_notification.html.erb
<% unless notification.read %>
  <div class="notification">
    <p><%= formatted_notification(notification) %></p>
    <p><%= "#{time_ago_in_words(notification.created_at)} ago." unless notification.created_at.nil? %></p>

    <%= form_for [notification.user, notification] do |f| %>
      <%= f.hidden_field :read, :value => true %>
      <%= f.submit 'Dismiss', :class => 'link' %>
    <% end %>
  </div>
<% end %>

app/views/dashboards/index.html.erb
<% content_for :title do %>
  dashboard - chessable
<% end %>

<section class="eight columns alpha" id="notifications">
  <h2 class="underlined_header">Notifications<%= " (#{@user.unread_notifications.count})" unless @user.unread_notifications.empty? %></h2>
  <% if @user.unread_notifications.empty? %>
  <p>You have no unread notifications.</p>
  <% else %>
    <% @user.unread_notifications.each do |notification| %>
      <%= render :partial => 'notification', :locals => { :notification => notification } %>
    <% end %>
  <% end %>
</section>

<section class="eight columns omega" id="game_invites">
  <h2 class="underlined_header">Game invites<%= " (#{@user.pending_game_invites.count})" unless @user.pending_game_invites.empty? %></h2>

  <% unless @user.pending_game_invites.empty? %>
    <p><strong>Received invites:</strong>
    <% @user.pending_game_invites.each do |game_invite| %>
      <div class="game_invite">
        <p><%= link_to game_invite.inviter.username, user_path(game_invite.inviter) %> has invited you to a game.<br>
          <%= link_to 'Click here', game_invite_path(game_invite) %> to view the invitation.</p>
      </div>
    <% end %>
  <% end %>

  <% unless @user.sent_invites.empty? %>
    <p><strong>Sent invites:</strong></p>
    <% @user.sent_invites.each do |game_invite| %>
      <div class="game_invite">
        <p>You are awaiting a response from <%= link_to game_invite.invited.username, user_path(game_invite.invited.username)%>.<br>
          <%= link_to 'Click here', game_invite_path(game_invite), :method => :delete, :confirm => 'Are you sure you want to cancel this game invite?' %>
          to cancel this invite.</p>
      </div>
    <% end %>
  <% end %>

  <% if @user.pending_game_invites.empty? && @user.sent_invites.empty? %>
    <p>You have no current game invites.</p>
  <% end %>

</section>

<div class="clear"></div>

<section class="sixteen columns alpha omega" id="active_games">
  <h2 class="underlined_header">Unfinished games</h2>
  <% if @user.active_games.empty? %>
    <p>You currently do not have any active games. Perhaps you should <%= link_to 'find an oppenent.', users_path %>
  <% else %>
    <div class="cols_container">
      <% col_counter = 0 %>
      <% @user.active_games.each do |game| %>
        <% col_counter = col_counter + 1 %>
        <%= render :partial => 'shared/game_preview', :locals => { :game => game } %>
        <% if (col_counter % 4) == 0 %>
          <div class="clear"></div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</section>

<div class="clear"></div>

<% unless @user.won_games.empty? %>
  <section class="sixteen columns alpha omega" id="games_won">
    <h2 class="underlined_header">Games won</h2>
    <div class="cols_container">
      <% @user.won_games.first(3).each do |game| %>
      <%= render :partial => 'shared/game_preview', :locals => { :game => game } %>
      <% end %>
    </div>
    <% if @user.won_games.count > 3 %>
      <p class="view_all"><%= link_to 'View all won games...', games_path(:playername => @user.username, :result => 'won') %></p>
    <% end %>
  </section>
<% end %>

<div class="clear"></div>

<% unless @user.lost_games.empty? %>
  <section class="sixteen columns alpha omega" id="games_won">
    <h2 class="underlined_header">Games lost</h2>
    <div class="cols_container">
      <% @user.lost_games.first(3).each do |game| %>
      <%= render :partial => 'shared/game_preview', :locals => { :game => game } %>
      <% end %>
    </div>
    <% if @user.lost_games.count > 3 %>
      <p class="view_all"><%= link_to 'View all lost games...', games_path(:playername => @user.username, :result => 'lost') %></p>
    <% end %>
  </section>
<% end %>

<div class="clear"></div>

<% unless @user.drew_games.empty? %>
  <section class="sixteen columns alpha omega" id="games_won">
    <h2 class="underlined_header">Games drew</h2>
    <div class="cols_container">
      <% @user.drew_games.first(3).each do |game| %>
      <%= render :partial => 'shared/game_preview', :locals => { :game => game } %>
      <% end %>
    </div>
    <% if @user.drew_games.count > 3 %>
      <p class="view_all"><%= link_to 'View all drawn games...', games_path(:playername => @user.username, :result => 'draw') %></p>
    <% end %>
  </section>
<% end %>