config/routes.rb
Chessable::Application.routes.draw do

  get "subscriptions/new"

  root :to => 'home#index'
  match '/forbidden' => 'home#forbidden', :as => :forbidden
  match '/terms' => 'home#terms', :as => :terms
  match '/privacy' => 'home#privacy', :as => :privacy
  match '/more-info' => 'home#more_info', :as => :more_info

  resources :users, :path => :players do
    match '/dashboard' => 'dashboards#index'
    
    collection do
      get 'random'
    end

    resources :notifications, :only => [:update]
    resources :subscriptions, :only => [:new]
  end

  resources :games, :except => [:new, :edit] do
    resources :comments, :only => [:create]
  end

  resources :game_invites, :only => [:create, :update, :show, :destroy]
  resources :sessions
  resources :password_resets
  resources :payment_notifications, :only => [:create]

  resources :verifications, :only => [:index]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <link rel="apple-touch-icon-precomposed" href="<%= image_path 'chessable-touch-icon.png' %>" />
  
    <% if Rails.env.production? %>

      <!-- start Mixpanel --><script type="text/javascript">(function(d,c){var a,b,g,e;a=d.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===d.location.protocol?"https:":"http:")+'//api.mixpanel.com/site_media/js/api/mixpanel.2.js';b=d.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b);c._i=[];c.init=function(a,d,f){var b=c;"undefined"!==typeof f?b=c[f]=[]:f="mixpanel";g="disable track track_links track_forms register register_once unregister identify name_tag set_config".split(" ");for(e=0;e<
        g.length;e++)(function(a){b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,0)))}})(g[e]);c._i.push([a,d,f])};window.mixpanel=c})(document,[]);
      mixpanel.init("4f872df52e477cc99100e3bd1c8d60bf");</script><!-- end Mixpanel -->

      <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-17945991-10']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

      </script>
  <% end %>
  
  <% if content_for? :title %>
    <title><%= yield :title %></title>
  <% else %>
    <title>chessable - play anyone, anywhere</title>
  <% end %>

</head>
<body id="<%= params[:controller].parameterize %>_controller">
  <div id="wrap">
    <div id="main">
      <%= render :partial => 'shared/header' %>

      <% if flash[:notice] %>
        <div class="container flash">
          <div class="sixteen columns notice">
            <p><%= flash[:notice] %> <input type="button" name="hide_flash" value="(dismiss)" id="hide_flash"></p>
          </div>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="container flash">
          <div class="sixteen columns alert">
            <p><%= flash[:alert] %> <input type="button" name="hide_flash" value="(dismiss)" id="hide_flash"></p>
          </div>  
        </div>
      <% end %>

      <div class="container">
        <div class="sixteen columns">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  <footer>
    <div class="container">
      <div class="sixteen columns">
        <p id="right_link" class="right">&copy; 2012 <%= link_to 'chessable', root_path %> &mdash; All rights reserved 
          <small><%= link_to '(more info)', more_info_path %></small></p>
        <ul class="left">
          <li><%= mail_to 'hello@chessable.co.uk', 'Contact' %></li>
          <li><%= mail_to 'hello@chessable.co.uk', 'Report a Bug', :subject => 'Bug Report' %></li>
          <li><%= link_to 'Terms of Service', terms_path %></li>
          <li><%= link_to 'Privacy Policy', privacy_path %></li>
        </ul>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<style type="text/css">
		body {
			background-color: #f9f9f9;
			font: sans-serif;
			line-height: 22px;
			font-size: 14px;
			color: #000;
		}
		h1 { font-size: 36px; line-height: 110%; color: #8d327f; }
		h2 { font-size: 24px; }

		a {
			color: #CC2A41;
			text-decoration: none;
		}
		a:hover { text-decoration: none; }

		table.box_panel {
			max-width: 618px;
			width: 70%;
			margin: 22px auto;
			padding: 11px;
			border: 1px solid #999;
			background-color: #E9EFF7;
		}
		td { font: 14px/22px sans-serif; padding-bottom: 11px; }
		p {
			font: 14px/22px sans-serif: margin-bottom: 22px;
		}
		table.box_panel.no_decoration {
			background-color: transparent;
			border: none;
		}

	</style>
</head>
<body>
	<table class="box_panel">
		<%= yield %>
	</table>

	<table class="box_panel no_decoration">
		<tr>
			<td>
				<p><strong>Contact:</strong><br>
					Email: <a href="mailto:hello@chessable.co.uk">hello@chessable.co.uk</a>				
				</p>
				<p>If you want to change your email preferences, visit your account settings
				on <a href="https://www.chessable.co.uk">www.chessable.co.uk</a>.</p>
			</td>
		</tr>
	</table>
</html>